const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
function setup(){
 const elements=new Map();function element(id){if(!elements.has(id))elements.set(id,{value:'',checked:true,style:{},listeners:{},addEventListener(t,l){this.listeners[t]=l;},append(){},replaceChildren(){},setAttribute(){},getAttribute(){return null;},removeAttribute(){}});return elements.get(id);}
 const context=vm.createContext({document:{getElementById:element,createElement:()=>element('scratch')},fetch:()=>new Promise(()=>{}),setInterval(){}});
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/paperclean/lab_static/lab.js'),'utf8'),context);
 vm.runInContext(`state.documents=[{id:'first',pages:[{number:1},{number:2}]},{id:'second',pages:[{number:1}]}];state.versions=[{id:'v1',document_id:'first',number:1,status:'complete',page_runs:{'1':'r1','2':'r2'}},{id:'v2',document_id:'second',number:1,status:'complete',page_runs:{'1':'r3'}}];state.runs=[{id:'r1',document_id:'first',page:1,status:'complete',review:{issues:[]},judgments:{},comments:{},notes:''},{id:'r2',document_id:'first',page:2,status:'complete',review:{issues:[]},judgments:{},comments:{},notes:''},{id:'r3',document_id:'second',page:1,status:'complete',review:{issues:[]},judgments:{},comments:{},notes:''}];documentId='first';versionId='v1';pageNumber=2;connected=true;renderAll=()=>{};refresh=async()=>{};calls=[];api=async(url,body)=>{calls.push({url,body});return url.includes('/judgments')?{...runById(url.split('/')[3]),...body}:{id:'next'};};`,context);
 element('image-model').value='codex/gpt-6.1-sol';element('generation-prompt').value='restore';element('review-prompt').value='review';return{context,element};
}
test('switching documents selects that document version and page, never a stale run',async()=>{const {context}=setup();await vm.runInContext("selectDocument('second')",context);assert.equal(vm.runInContext('pageNumber',context),1);assert.equal(vm.runInContext('activeRun().id',context),'r3');assert.equal(vm.runInContext('versionId',context),'v2');await vm.runInContext("createVersion('restore')",context);const c=vm.runInContext('calls.at(-1)',context);assert.equal(c.body.document_id,'second');assert.equal(c.body.mode,'restore');assert.equal(c.body.candidate,undefined);});
test('switching pages selects its restoration and saves pending feedback first',async()=>{const {context}=setup();vm.runInContext("draft(activeRun()).notes='Page 2 instruction';changed(activeRun());",context);await vm.runInContext('selectPage(1)',context);assert.equal(vm.runInContext('activeRun().id',context),'r1');const c=vm.runInContext('calls[0]',context);assert.equal(c.url,'/api/runs/r2/judgments');assert.equal(c.body.notes,'Page 2 instruction');});
test('refinement flushes comments and decisions before starting the next version',async()=>{const {context}=setup();vm.runInContext("draft(activeRun()).comments={'1':'Preserve the source spelling'};draft(activeRun()).judgments={'1':'false_alarm'};changed(activeRun());",context);await vm.runInContext("createVersion('refine',[2])",context);const c=vm.runInContext('calls',context);assert.equal(c[0].url,'/api/runs/r2/judgments');assert.equal(c[0].body.comments['1'],'Preserve the source spelling');assert.equal(c[1].url,'/api/versions');assert.equal(c[1].body.parent_version_id,'v1');assert.equal(c[1].body.pages[0],2);});
test('failed feedback save blocks a source change',async()=>{const {context,element}=setup();vm.runInContext("draft(activeRun()).notes='Pending';changed(activeRun());api=async()=>{throw new Error('Save failed');};",context);await vm.runInContext("selectDocument('second')",context);assert.equal(vm.runInContext('documentId',context),'first');assert.equal(element('message').textContent,'Save failed');});
test('full document downloads remain enabled while models are running',()=>{const {context,element}=setup();vm.runInContext("state.runs[0].status='restoring';renderLibrary();controls();",context);assert.equal(element('restore-document').disabled,true);assert.equal(element('refine-document').disabled,true);assert.equal(element('download-document').hidden,false);assert.equal(element('download-document').href,'/api/documents/first/export.pdf?version=v1');});
