"use strict";
const $ = id => document.getElementById(id);
const el = (tag, text, cls) => {const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let state={documents:[],runs:[],versions:[],defaults:{}}, documentId=null, versionId='source', pageNumber=1, selectedIssue=null, connected=false, starting=false, lastView='';
const drafts=new Map();
const activeDocument=()=>state.documents.find(d=>d.id===documentId);
const documentVersions=()=>state.versions.filter(v=>v.document_id===documentId).sort((a,b)=>a.number-b.number);
const activeVersion=()=>documentVersions().find(v=>v.id===versionId);
const latestVersion=()=>documentVersions().at(-1);
const runById=id=>state.runs.find(r=>r.id===id);
const activeRun=()=>runById(activeVersion()?.page_runs[String(pageNumber)]);
const busy=r=>r&&['queued','restoring','reviewing'].includes(r.status);
function displayRun(r=activeRun()){return r?.restored_url?r:r?.parent_run_id?displayRun(runById(r.parent_run_id)):null;}
function repairRun(r){return r?.status==='complete'?r:r&&['failed','interrupted'].includes(r.status)&&!r.restored_url?repairRun(runById(r.parent_run_id)):null;}
function reviewRun(){const r=activeRun();return r?.review?r:!r?.restored_url?displayRun(r):null;}
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').className=`message${error?' error':''}`;}
async function api(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error||`Request failed (${r.status})`);return v;}
function draft(r){if(!drafts.has(r.id))drafts.set(r.id,{judgments:{...r.judgments},comments:{...r.comments},notes:r.notes||'',dirty:false,revision:0});return drafts.get(r.id);}
function changed(r){const d=draft(r);d.dirty=true;d.revision++;$('feedback-status').textContent='Unsaved feedback';controls();}
let saveQueue=Promise.resolve();
async function saveFeedback(r=reviewRun()){
  if(!r)return;const d=draft(r);if(!d.dirty)return;const revision=d.revision;
  const body={judgments:{...d.judgments},comments:{...d.comments},notes:d.notes};
  const operation=saveQueue.catch(()=>{}).then(()=>api(`/api/runs/${r.id}/judgments`,body));saveQueue=operation;
  const saved=await operation;const index=state.runs.findIndex(x=>x.id===r.id);if(index>=0)state.runs[index]=saved;
  if(d.revision===revision)d.dirty=false;
  if(reviewRun()?.id===r.id)$('feedback-status').textContent=d.dirty?'Unsaved feedback':'Feedback saved';
  controls();
}
async function flushDrafts(){for(const r of state.runs.filter(r=>r.document_id===documentId))await saveFeedback(r);}
function repairs(r){if(!r||r.status!=='complete')return false;const d=draft(r);return Object.values(d.judgments).includes('confirmed')||Object.values(d.comments).some(c=>c.trim())||Boolean(d.notes.trim());}
function markedPages(){const v=activeVersion();return activeDocument()?.pages.filter(p=>repairs(repairRun(runById(v?.page_runs[String(p.number)])))).map(p=>p.number)||[];}
function controls(){const doc=activeDocument(),running=state.runs.some(r=>r.document_id===documentId&&busy(r));const ready=doc&&connected&&$('approved').checked&&!starting&&!running;const latest=versionId===latestVersion()?.id;
 $('restore-document').disabled=!ready;$('refine-document').disabled=!ready||!latest||!markedPages().length;$('refine-page').disabled=!ready||!latest||!repairs(repairRun(activeRun()));
 $('save-feedback').disabled=!reviewRun()||busy(activeRun());$('notes').disabled=busy(activeRun());$('previous-page').disabled=!doc||pageNumber<=1;$('next-page').disabled=!doc||pageNumber>=doc.pages.length;
 $('call-count').textContent=doc?`Restore: up to ${doc.pages.length*2} requests · refine marked pages: up to ${markedPages().length*2}`:'';
}
async function selectDocument(id){try{await flushDrafts();documentId=id;versionId=latestVersion()?.id||'source';pageNumber=1;selectedIssue=null;message('');renderAll();}catch(e){message(e.message,true);}}
async function selectPage(page){try{await flushDrafts();pageNumber=Number(page);selectedIssue=null;message('');renderAll();}catch(e){message(e.message,true);}}
async function selectVersion(id){try{await flushDrafts();versionId=id;selectedIssue=null;message('');renderAll();}catch(e){message(e.message,true);}}
function renderLibrary(){
 $('doc-count').textContent=state.documents.length;
 $('documents').replaceChildren(...state.documents.map(d=>{const b=el('button',undefined,`document-card${d.id===documentId?' active':''}`);const im=el('img');im.src=d.pages[0].url;im.alt='';const c=el('div',undefined,'card-copy');c.append(el('strong',d.name),el('span',`${d.pages.length} ${d.pages.length===1?'page':'pages'}`));b.append(im,c);b.addEventListener('click',()=>selectDocument(d.id));return b;}));
 const doc=activeDocument();$('page-count').textContent=doc?.pages.length||0;
 $('pages').replaceChildren(...(doc?.pages||[]).map(p=>{const r=runById(activeVersion()?.page_runs[String(p.number)]),b=el('button',undefined,`page-card${p.number===pageNumber?' active':''}`);const im=el('img');im.src=p.url;im.alt='';const c=el('div',undefined,'card-copy');c.append(el('strong',`Page ${p.number}`),el('span',r?`${r.status} · ${r.review?.issues.length??'—'} findings`:'Original'));b.append(im,c);b.addEventListener('click',()=>selectPage(p.number));return b;}));
 $('document-title').textContent=doc?.name||'Your document, restored.';
 const opts=[el('option','Original')];opts[0].value='source';for(const v of documentVersions()){const o=el('option',`${v.name} · ${v.status.replaceAll('_',' ')}`);o.value=v.id;opts.push(o);} $('version').replaceChildren(...opts);$('version').value=versionId;
 const pages=(doc?.pages||[]).map(p=>{const o=el('option',String(p.number));o.value=p.number;return o;});$('page').replaceChildren(...pages);$('page').value=pageNumber;
 const v=activeVersion();$('version-status').textContent=doc?`${v?.restored_pages||0} / ${doc.pages.length} restored pages · ${v?.status?.replaceAll('_',' ')||'original document'}${versionId!==latestVersion()?.id&&v?' · viewing history':''}`:'';
 $('download-document').hidden=!doc;if(doc)$('download-document').href=`/api/documents/${doc.id}/export.pdf?version=${versionId}`;
}
function setImage(id,wrap,empty,url){const image=$(id);$(wrap).style.display=url?'block':'none';$(empty).hidden=Boolean(url);if(url){if(image.getAttribute('src')!==url)image.src=url;}else image.removeAttribute('src');}
function svgNode(tag,attrs){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;}
function renderBoxes(){const rows=reviewRun()?.review?.issues||[];for(const [svgId,imgId,key]of [['source-boxes','source-image','source_box'],['restored-boxes','restored-image','restored_box']]){const svg=$(svgId),im=$(imgId);svg.replaceChildren();svg.style.display=$('show-boxes').checked?'block':'none';if(!im.naturalWidth)return;svg.setAttribute('viewBox',`0 0 ${im.naturalWidth} ${im.naturalHeight}`);for(const issue of rows){const b=issue[key];if(!b)continue;const x=b.x0*im.naturalWidth,y=b.y0*im.naturalHeight,w=(b.x1-b.x0)*im.naturalWidth,h=(b.y1-b.y0)*im.naturalHeight,fs=Math.max(15,im.naturalWidth/45),ly=Math.max(0,y-fs*1.2);const g=svgNode('g',{role:'button',tabindex:'0','aria-label':`Issue ${issue.id}: ${issue.label}`}),title=svgNode('title',{});title.textContent=`${issue.label}\n${issue.description}\nClick to inspect and add feedback`;const rect=svgNode('rect',{x,y,width:w,height:h,stroke:issue.color,fill:issue.color,class:`issue-box${selectedIssue===issue.id?' selected-box':''}`}),badge=svgNode('rect',{x,y:ly,width:fs*1.6,height:fs*1.2,fill:issue.color}),text=svgNode('text',{x:x+fs*.25,y:ly+fs*.88,fill:'white','font-size':fs});text.textContent=issue.id;g.append(title,rect,badge,text);g.addEventListener('click',()=>selectIssue(issue.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectIssue(issue.id);}});svg.append(g);}}}
function renderIssues(){const r=reviewRun(),review=r?.review;$('issue-count').textContent=review?.issues.length??'—';$('review-summary').textContent=review?.summary||'Findings appear after each independent review.';
 if(!review?.issues.length){const tr=el('tr'),td=el('td',review?'No issues detected. Inspect the page for missed defects.':'This page has no completed review yet.','table-empty');td.colSpan=4;tr.append(td);$('issues').replaceChildren(tr);return;}
 const d=draft(r);$('issues').replaceChildren(...review.issues.map(issue=>{const tr=el('tr',undefined,selectedIssue===issue.id?'selected':'');const marker=el('td'),key=el('span',String(issue.id),'box-key');key.style.backgroundColor=issue.color;marker.append(key);const finding=el('td');finding.append(el('div',issue.label,'finding-title'),el('div',issue.description,'description'),el('div',`Source: ${issue.source_evidence}`,'evidence'));
 const decision=el('td'),buttons=el('div',undefined,'decision-buttons');for(const [value,label]of [['confirmed','Accept issue'],['false_alarm','Dismiss']]){const b=el('button',label,`decision${d.judgments[issue.id]===value?' chosen':''}`);b.setAttribute('aria-label',`${label} ${issue.id}`);b.setAttribute('aria-pressed',String(d.judgments[issue.id]===value));b.disabled=busy(activeRun());b.addEventListener('click',async e=>{e.stopPropagation();d.judgments[issue.id]=d.judgments[issue.id]===value?'unrated':value;changed(r);renderIssues();try{await saveFeedback(r);}catch(error){message(error.message,true);}});buttons.append(b);}decision.append(buttons);
 const cell=el('td'),comment=el('textarea');comment.rows=2;comment.maxLength=4000;comment.placeholder='Clarify the repair…';comment.value=d.comments[issue.id]||'';comment.setAttribute('aria-label',`Comment for issue ${issue.id}`);comment.disabled=busy(activeRun());comment.addEventListener('click',e=>e.stopPropagation());comment.addEventListener('input',()=>{d.comments[issue.id]=comment.value;changed(r);});comment.addEventListener('change',()=>saveFeedback(r).catch(e=>message(e.message,true)));cell.append(comment);
 tr.append(marker,finding,decision,cell);marker.addEventListener('click',()=>selectIssue(issue.id));finding.addEventListener('click',()=>selectIssue(issue.id));return tr;}));}
function crop(canvasId,imgId,b){const c=$(canvasId),im=$(imgId);c.hidden=!b;if(!b||!im.complete||!im.naturalWidth)return;const pad=.012,x=Math.max(0,b.x0-pad)*im.naturalWidth,y=Math.max(0,b.y0-pad)*im.naturalHeight,w=Math.min(1,b.x1+pad)*im.naturalWidth-x,h=Math.min(1,b.y1+pad)*im.naturalHeight-y,scale=Math.min(3,1000/w,500/h);c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));c.getContext('2d').drawImage(im,x,y,w,h,0,0,c.width,c.height);}
function renderDetail(){const i=reviewRun()?.review?.issues.find(i=>i.id===selectedIssue);$('issue-detail').hidden=!i;if(!i)return;$('detail-title').textContent=`Issue ${i.id} · ${i.label}`;$('detail-title').style.color=i.color;crop('source-crop','source-image',i.source_box);crop('restored-crop','restored-image',i.restored_box);$('source-crop-unavailable').hidden=Boolean(i.source_box);}
function selectIssue(id){selectedIssue=id;renderBoxes();renderDetail();$('issue-detail').scrollIntoView({behavior:'smooth',block:'nearest'});}
function viewKey(){const r=activeRun();return JSON.stringify([documentId,versionId,pageNumber,r?.status,r?.restored_url,r?.review?.issues.length]);}
function renderPage(){const doc=activeDocument(),p=doc?.pages.find(p=>p.number===pageNumber),r=activeRun(),display=displayRun(),review=reviewRun();setImage('source-image','source-wrap','source-empty',p?.url);setImage('restored-image','restored-wrap','restored-empty',display?.restored_url);
 $('result-title').textContent=doc?`Page ${pageNumber} of ${doc.pages.length}`:'Choose a document';$('result-status').textContent=r?.status||'Original';$('source-dimensions').textContent=p?`${p.width} × ${p.height}`:'';$('restored-dimensions').textContent=display?.dimensions?.restored.join(' × ')||'';$('candidate-label').textContent=busy(r)&&display?.id!==r.id?'Previous restoration · repair in progress':'Current restoration';
 $('progress').hidden=!busy(r);$('progress-title').textContent=r?.status==='restoring'?(r.parent_run_id?'Refining this page':'Restoring this page'):r?.status==='reviewing'?'Reviewing with GPT-6.1 Sol High':'Page queued';
 $('notes-field').hidden=!review;$('notes').value=review?draft(review).notes:'';$('feedback-status').textContent=review&&draft(review).dirty?'Unsaved feedback':'';$('download-composite').hidden=!r?.composite_url;if(r?.composite_url)$('download-composite').href=r.composite_url;
 if(r?.error)message(r.error,true);renderIssues();renderBoxes();renderDetail();controls();lastView=viewKey();}
function renderAll(){renderLibrary();renderPage();}
async function refresh(initial=false){state=await api('/api/state');if(initial){$('generation-prompt').value=state.defaults.generation_prompt;$('review-prompt').value=state.defaults.review_prompt;$('image-model').value=state.defaults.image_model;documentId=state.documents[0]?.id||null;versionId=latestVersion()?.id||'source';renderAll();}else{renderLibrary();if(lastView!==viewKey())renderPage();controls();}}
async function createVersion(mode,pages){starting=true;controls();try{await flushDrafts();const v=await api('/api/versions',{document_id:documentId,mode,parent_version_id:versionId,approved:$('approved').checked,image_model:$('image-model').value,generation_prompt:$('generation-prompt').value,review_prompt:$('review-prompt').value,...(pages?{pages}:{})});await refresh();versionId=v.id;selectedIssue=null;message('');renderAll();}catch(e){message(e.message,true);}finally{starting=false;controls();}}
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(new Error('Cannot read file'));reader.readAsDataURL(file);});}
$('documents-input').addEventListener('change',async e=>{starting=true;controls();try{await flushDrafts();for(const file of Array.from(e.target.files)){if(file.size>40*1024*1024)throw new Error('Choose files smaller than 40 MiB');message(`Importing ${file.name}…`);const d=await api('/api/documents',{filename:file.name,data:await fileData(file)});await refresh();documentId=d.id;versionId='source';pageNumber=1;selectedIssue=null;}renderAll();message('Document ready. Restore it to begin reviewing.');}catch(error){message(error.message,true);}finally{e.target.value='';starting=false;controls();}});
$('page').addEventListener('change',()=>selectPage($('page').value));$('version').addEventListener('change',()=>selectVersion($('version').value));$('previous-page').addEventListener('click',()=>selectPage(pageNumber-1));$('next-page').addEventListener('click',()=>selectPage(pageNumber+1));$('approved').addEventListener('change',controls);
$('restore-document').addEventListener('click',()=>createVersion('restore'));$('refine-document').addEventListener('click',()=>createVersion('refine'));$('refine-page').addEventListener('click',()=>createVersion('refine',[pageNumber]));$('save-feedback').addEventListener('click',()=>saveFeedback().catch(e=>message(e.message,true)));
$('notes').addEventListener('input',()=>{const r=reviewRun();if(r){draft(r).notes=$('notes').value;changed(r);}});$('notes').addEventListener('change',()=>saveFeedback().catch(e=>message(e.message,true)));
$('reset-prompts').addEventListener('click',()=>{$('generation-prompt').value=state.defaults.generation_prompt;$('review-prompt').value=state.defaults.review_prompt;});$('show-boxes').addEventListener('change',renderBoxes);$('zoom').addEventListener('change',()=>{for(const id of ['source-wrap','restored-wrap'])$(id).style.width=`${Number($('zoom').value)*100}%`;});
for(const id of ['source-image','restored-image'])$(id).addEventListener('load',()=>{renderBoxes();renderDetail();});$('close-detail').addEventListener('click',()=>{selectedIssue=null;renderBoxes();renderDetail();});
async function checkConnection(){try{const c=await api('/api/capabilities');connected=c.ready;$('connection').textContent=c.message;$('connection').className=`connection ${connected?'ready':'error'}`;}catch{connected=false;$('connection').textContent='Local server unavailable';}controls();}
async function initialize(){try{await refresh(true);await checkConnection();setInterval(()=>refresh().catch(e=>message(e.message,true)),2500);setInterval(checkConnection,30000);}catch(e){message(e.message,true);}}
initialize();
